//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::TuCalendar::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::TuCalendar::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->MySplitView = safe_cast<::Windows::UI::Xaml::Controls::SplitView^>(__target);
        }
        break;
    case 3:
        {
            this->IconListbox = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(this->IconListbox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::TuCalendar::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::IconListbox_SelectionChanged);
        }
        break;
    case 4:
        {
            this->WelcomeTab = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 5:
        {
            this->MonthViewTab = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 6:
        {
            this->WeekViewTab = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 7:
        {
            this->ScheduleTab = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 8:
        {
            this->tst = safe_cast<::Windows::UI::Xaml::Controls::DatePicker^>(__target);
        }
        break;
    case 9:
        {
            this->main = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
        }
        break;
    case 10:
        {
            this->schedule = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
        }
        break;
    case 11:
        {
            this->MyButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->MyButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::TuCalendar::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MyButton_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::TuCalendar::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


