#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class RelativePanel;
                ref class ListView;
                ref class TextBlock;
                ref class ComboBox;
            }
        }
    }
}

namespace TuCalendar
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MonthView : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ DateBox;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName0;
        private: ::Windows::UI::Xaml::Controls::ListView^ SundayList;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName1;
        private: ::Windows::UI::Xaml::Controls::ListView^ MondayList;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName2;
        private: ::Windows::UI::Xaml::Controls::ListView^ TuesdayList;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName3;
        private: ::Windows::UI::Xaml::Controls::ListView^ WednesdayList;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName4;
        private: ::Windows::UI::Xaml::Controls::ListView^ ThursdayList;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName5;
        private: ::Windows::UI::Xaml::Controls::ListView^ FridayList;
        private: ::Windows::UI::Xaml::Controls::Grid^ WeekName6;
        private: ::Windows::UI::Xaml::Controls::ListView^ SaturdayList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sat5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSat5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sat4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSat4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sat3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSat3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sat2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSat2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sat1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSat1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sat0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSat0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Fri5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarFri5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Fri4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarFri4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Fri3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarFri3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Fri2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarFri2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Fri1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarFri1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Fri0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarFri0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thur5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarThur5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thur4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarThur4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thur3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarThur3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thur2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarThur2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thur1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarThur1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thur0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarThur0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wed5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarWed5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wed4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarWed4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wed3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarWed3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wed2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarWed2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wed1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarWed1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wed0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarWed0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tue5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarTue5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tue4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarTue4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tue3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarTue3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tue2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarTue2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tue1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarTue1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tue0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarTue0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Mon5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarMon5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Mon4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarMon4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Mon3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarMon3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Mon2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarMon2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Mon1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarMon1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Mon0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarMon0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sun5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSun5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sun4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSun4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sun3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSun3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sun2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSun2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sun1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSun1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sun0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LunarSun0;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ yeartxt;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ monthtxt;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ daytxt;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SelectedYear;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SelectedMonth;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SelectedDay;
    };
}

