#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class ListView;
                ref class TextBlock;
                ref class RelativePanel;
                ref class ComboBox;
            }
        }
    }
}

namespace TuCalendar
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class WeekView : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ DayTimePart;
        private: ::Windows::UI::Xaml::Controls::Grid^ Control;
        private: ::Windows::UI::Xaml::Controls::ListView^ SundayList;
        private: ::Windows::UI::Xaml::Controls::ListView^ MondayList;
        private: ::Windows::UI::Xaml::Controls::ListView^ TuesdayList;
        private: ::Windows::UI::Xaml::Controls::ListView^ WednesdayList;
        private: ::Windows::UI::Xaml::Controls::ListView^ ThursdayList;
        private: ::Windows::UI::Xaml::Controls::ListView^ FridayList;
        private: ::Windows::UI::Xaml::Controls::ListView^ SaturdayList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Saturday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ SaturdayLunar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Friday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FridayLunar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Thursday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ThursdayLunar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Wednesday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ WednesdayLunar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Tuesday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TuesdayLunar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Monday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ MondayLunar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Sunday;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ SundayLunar;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ DateBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ yeartxt;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ monthtxt;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ daytxt;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SelectedYear;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SelectedMonth;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SelectedDay;
    };
}

